services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto_broker
    ports:
      - "1883:1883"
    volumes:
      - ./infra/mosquitto.conf:/mosquitto/config/mosquitto.conf:Z
      - ./infra/data:/mosquitto/data:Z
      - ./infra/log:/mosquitto/log:Z
    restart: always

  simulator:
    build: ./edge
    container_name: mqtt_simulator
    environment:
      - MQTT_BROKER=mosquitto
    depends_on:
      - mosquitto

  backend:
    build: ./backend
    container_name: open_pmf_backend
    environment:
      - MQTT_BROKER_URL=tcp://mosquitto:1883
    ports:
      - "8080:8080"
    depends_on:
      - mosquitto