version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto_broker
    ports:
      - "1883:1883"
    volumes:
      - ./infra/mosquitto.conf:/mosquitto/config/mosquitto.conf:Z
      - mosquitto_data:/mosquitto/data
    restart: always

  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: timescaledb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=openpmf
    ports:
      - "5432:5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    restart: always

  backend:
    build: ./backend
    container_name: open_pmf_backend
    ports:
      - "8080:8080"
    environment:
      - MQTT_BROKER_URL=tcp://mosquitto:1883
      - SPRING_DATASOURCE_URL=jdbc:postgresql://timescaledb:5432/openpmf
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - mosquitto
      - timescaledb

  simulator:
    build: ./edge
    container_name: mqtt_simulator
    depends_on:
      - mosquitto

# Secção de volumes globais
volumes:
  timescaledb_data:
  mosquitto_data: