apiVersion: 1
datasources:
  - name: PostgreSQL
    type: postgres
    uid: openpmf-ds
    url: timescaledb:5432
    database: openpmf
    user: admin
    secureJsonData:
      password: admin_pass
    jsonData:
      sslmode: 'disable'
      postgresVersion: 15
      timescaledb: true
    isDefault: true
    editable: true
